### ISSUE TITLE
[enhancement]: Would be nice to have amend option

### ISSUE THREAD

**Issue by Kotsuha** [pragma-git/pragma-git#6]
### The problem

It seems like there is no way to amend last commit. Do you plan to support that?

This software seems like it wants to keep the interface very simple. ~~It'd be an interesting topic to think about what you want to have and not have.~~ → I mean it's an interesting question to think about. Not that I want to have a discussion conversation here :)

### The solution

N/A

### Alternatives

N/A

**Comment by pragma-git** [comment]
Thanks for the enhancement idea.  I also think an amend function is useful, so it is definitely lacking, and something I will add.

1) I do have some problems on how to make amending commits simple and safe, since I am concerned how to best handle modifications to commits that have been pushed to remote.  This concern is not only for amending commits, but in general.  Maybe a warning dialog that pops up for commits that have been synced to the remote? Suggestions are welcome!

2) It is true that my aim is to make the interface simple, but I also wish to incorporate more features.  I have been thinking of maybe adding a 'Pro' button, giving a dropdown menu.  Under that button, things such as amending commits, reseting commits, etc could be accessible. 

I would appreciate to bounce ideas on the interface and missing functionality with you.  Please indicate if you would be comfortable with me reaching out to you (email is available on-line in github repositories). Otherwise, please keep up the good suggestions here

**Comment by pragma-git** [comment]
Fixed in current version
